---
baseURL: '/cawemo/latest/'
languageCode: 'en-us'
title: 'Cawemo'
theme: 'camunda'

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: 'get-started'
      name: 'Get Started'
      url: '/get-started'
    - id: 'manual'
      name: 'BPM Platform'
      url: '/manual'
    - id: 'optimize'
      name: 'Optimize'
      url: '/optimize'
    - id: 'cawemo'
      name: 'Cawemo'
      url: '/cawemo'
    - id: 'enterprise'
      name: 'Enterprise'
      url: '/enterprise'
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: 'cawemo'
    version: 'latest'
    versionAlias: '1.0'
    versions:
      - 'latest'
      - 'develop'
  github:
    repositoryName: 'camunda/camunda-docs-cawemo'
    branch: 'master'

outputs:
  home:
    - 'HTML'
    - 'RSS'
  section:
    - 'HTML'

disableKinds:
  - taxonomy
  - taxonomyTerm
...
