---
baseURL: '/cawemo/develop/'
languageCode: 'en-us'
title: 'Cawemo'
theme: 'camunda'

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: 'get-started'
      name: 'Get Started'
      url: '/get-started'
    - id: 'manual'
      name: 'BPM Platform'
      url: '/manual'
    - id: 'optimize'
      name: 'Optimize'
      url: '/optimize'
    - id: 'cawemo'
      name: 'Cawemo'
      url: '/cawemo'
    - id: 'enterprise'
      name: 'Enterprise'
      url: '/enterprise'
    - id: 'security'
      name: 'Security'
      url: '/security'
  section:
    id: 'cawemo'
    version: '1.4'
    versions:
      - 'latest'
      - '1.4'
      - '1.3'
      - '1.2'
      - '1.1'
      - '1.0'
      - 'develop'
  github:
    repositoryName: 'camunda/camunda-docs-cawemo'
    branch: 'master'

outputs:
  home:
    - 'HTML'
    - 'RSS'
  section:
    - 'HTML'

disableKinds:
  - taxonomy
  - taxonomyTerm
