version: '3.6'
services:
  restapi:
    image: registry.camunda.cloud/cawemo-ee/cawemo-restapi:1.5.1
    container_name: cawemo-restapi
    restart: always
    labels:
      - 'cawemo'
    environment:
      JAVA_OPTIONS: -Xmx256m
      CAWEMO_DB_HOST: $DB_HOST
      CAWEMO_DB_PORT: $DB_PORT
      CAWEMO_DB_NAME: $DB_NAME
      CAWEMO_DB_USER: $DB_USER
      CAWEMO_DB_PASSWORD: $DB_PASSWORD
      CAWEMO_MAIL_HOST: $SMTP_HOST
      CAWEMO_MAIL_PORT: $SMTP_PORT
      CAWEMO_MAIL_USER: $SMTP_USER
      CAWEMO_MAIL_PASSWORD: $SMTP_PASSWORD
      CAWEMO_MAIL_ENABLE_TLS: $SMTP_ENABLE_TLS
      CAWEMO_MAIL_FROM_ADDRESS: $SMTP_FROM_ADDRESS
      CAWEMO_MAIL_FROM_NAME: $SMTP_FROM_NAME
      CAWEMO_MIGRATION_MIGRATE: "true"
      CAWEMO_PUSHER_APP_ID: 1
      CAWEMO_PUSHER_KEY: 1
      CAWEMO_PUSHER_SECRET: $WEBSOCKET_SECRET
      CAWEMO_PUSHER_HOST: garufa
      CAWEMO_PUSHER_PORT: 8060
      CAWEMO_SERVER_CACHE_TEMPLATES: "true"
      CAWEMO_SERVER_SHUTDOWN_TIMEOUT: 9000
      CAWEMO_SERVER_URL: $SERVER_URL
      CLIENT_THEME_COLORS_PRIMARY: $THEME_COLOR_PRIMARY
      CLIENT_THEME_COLORS_SECONDARY: $THEME_COLOR_SECONDARY
      CLIENT_THEME_COLORS_ACCENT: $THEME_COLOR_ACCENT
      LICENSE_FILE_PATH: /config.key
    volumes:
      - ${HOST_LICENSE_FILE_PATH}:/config.key
    expose:
      - '8081'
    links:
      - garufa:garufa
  webapp:
    image: registry.camunda.cloud/cawemo-ee/cawemo-webapp:1.5.1
    container_name: cawemo-webapp
    restart: always
    labels:
      - 'cawemo'
    environment:
      NODE_ENV: production
      NODE_OPTIONS: "--max-old-space-size=128"
      PRODUCT_CONTEXT: enterprise
      REST_API_URL: http://restapi:8081
      REST_MANAGEMENT_API_URL: http://restapi:8091
      CLIENT_PUSHER_KEY: 1
      CLIENT_PUSHER_HOST: $BROWSER_WEBSOCKET_HOST
      CLIENT_PUSHER_PORT: $BROWSER_WEBSOCKET_PORT
      CLIENT_PUSHER_FORCETLS: $BROWSER_WEBSOCKET_FORCETLS
      CLIENT_THEME_COLORS_PRIMARY: $THEME_COLOR_PRIMARY
      CLIENT_THEME_COLORS_SECONDARY: $THEME_COLOR_SECONDARY
      CLIENT_THEME_COLORS_ACCENT: $THEME_COLOR_ACCENT
      CLIENT_THEME_LOGOPATH: $THEME_LOGO_URL
      NODE_SESSION_COOKIE_SECRET: $SERVER_SESSION_COOKIE_SECRET
      PUSHER_APP_ID: 1
      PUSHER_KEY: 1
      PUSHER_HOST: garufa
      PUSHER_SECRET: $WEBSOCKET_SECRET
      SERVER_HTTPS_ONLY: $SERVER_HTTPS_ONLY
      SERVER_HOST: $SERVER_HOST
      SERVER_URL: $SERVER_URL
      IAM_BASE_URL: $IAM_BASE_URL
      IAM_CAWEMO_CLIENT_ID: cawemo
      IAM_CAWEMO_CLIENT_SECRET: $CLIENT_SECRET
    ports:
      - '8080:8070'
    links:
      - restapi:restapi
      - garufa:garufa
  garufa:
    image: registry.camunda.cloud/cawemo-ee/cawemo-garufa:1.5.0
    container_name: cawemo-garufa
    restart: always
    labels:
      - 'cawemo'
    environment:
      APP_ID: 1
      APP_KEY: 1
      SECRET: $WEBSOCKET_SECRET
    ports:
      - '8060:8060'
  backend:
    image: registry.camunda.cloud/iam-ee/iam-backend:v1.0.2
    container_name: iam-backend
    environment:
      BACKEND_URL: $IAM_BASE_URL/api
      DATABASE_ENCRYPTION_KEY: $IAM_DATABASE_ENCRYPTION_KEY
      DB_URL: jdbc:postgresql://${IAM_DB_HOST}:${IAM_DB_PORT}/${IAM_DB_NAME}
      DB_USER: $IAM_DB_USER
      DB_PASSWORD: $IAM_DB_PASSWORD
      DEFAULT_CLIENT_BASE_URL: $SERVER_URL
      DEFAULT_CLIENT_ID: cawemo
      DEFAULT_CLIENT_LOGOUT_URL: ${SERVER_URL}/logout
      DEFAULT_CLIENT_NAME: Cawemo
      DEFAULT_CLIENT_SECRET: $CLIENT_SECRET
      EMAIL_NOREPLY_SENDER: $SMTP_FROM_ADDRESS
      EMAIL_SENDER: $SMTP_FROM_ADDRESS
      EMAIL_SENDER_NAME: $SMTP_FROM_NAME
      EMAIL_SUPPORT: ""
      ENFORCE_HTTPS: $SERVER_HTTPS_ONLY
      FRONTEND_URL: $IAM_BASE_URL
      SMTP_HOST: $SMTP_HOST
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_PORT: $SMTP_PORT
      SMTP_USER: $SMTP_USER
      SMTP_WITH_TLS: $SMTP_ENABLE_TLS
      TOKEN_ISSUER: $IAM_BASE_URL
      TOKEN_SIGNING_KEY: $IAM_TOKEN_SIGNING_KEY
    healthcheck:
      test: wget http://localhost:8081/actuator/health -q -O - > /dev/null 2>&1
      interval: 30s
      timeout: 15s
      retries: 5
  frontend:
    image: registry.camunda.cloud/iam-ee/iam-frontend:v1.0.2
    container_name: iam-frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: $IAM_BASE_URL/api
      BASE: $IAM_BASE_URL
      EMAIL_NOREPLY_SENDER: $SMTP_FROM_ADDRESS
      EMAIL_SUPPORT: ""
    healthcheck:
      test: wget http://localhost:80 -q -O - > /dev/null 2>&1
      interval: 30s
      timeout: 15s
      retries: 5
  router:
    image: registry.camunda.cloud/iam-ee/iam-router:v1.0.2
    container_name: iam-router
    depends_on:
      - backend
      - frontend
    environment:
      BACKEND_CONTAINER: backend:8080
      FRONTEND_CONTAINER: frontend:80
    ports:
      - 8090:80
    healthcheck:
      test: wget http://localhost:81 -q -O - > /dev/null 2>&1
      interval: 30s
      timeout: 15s
      retries: 5
