version: '3.6'
services:
  reverse-proxy:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "${SERVER_TLS_CERTIFICATES_PATH}:/etc/nginx/certs:ro"
    ports: ["0.0.0.0:443:443"]
    healthcheck:
      test: "echo Running"
      interval: 10s
    environment:
      HTTPS_METHOD: nohttp
  webapp:
    environment:
      SERVER_HTTPS_ONLY: "true"
      VIRTUAL_HOST: $SERVER_HOST
      VIRTUAL_PORT: 8070
  websockets:
    environment:
      VIRTUAL_HOST: $BROWSER_WEBSOCKET_HOST
  backend:
    environment:
      ENFORCE_HTTPS: "true"
  router:
    environment:
      VIRTUAL_HOST: $IAM_SERVER_HOST
