name: development

on:
  pull_request:
    branches: [master]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: asdf_install
        uses: asdf-vm/actions/install@v1

      - name: Check if hugo generation works
        run: hugo
